name: test

on:
  push:
    branches: [main]
  schedule:
   - cron : '0 * * * *'

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
 
      - name: Test Deno
        run:  panda=${{ secrets.panda }} deno run --allow-read --allow-env --allow-net cekcron.js


  
