name: test

on:
  push:
    branches: [main]
  schedule:
   - cron : '0 * * * *'

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: "1.8.2"

      - name: Test Deno
        run:  deno run --allow-read --allow-env --allow-net cekcron.js
        env:
         panda: ${{ secrets.panda }}

  
